server:
  port: 9004

spring:
  application:
    name: cloudalibaba-provider-payment
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    type: com.alibaba.druid.pool.DruidDataSource
    username: springcloud
    password: wgx
    driver-class-name: oracle.jdbc.driver.OracleDriver
    druid:
      #最大活跃数
      max-active: 20
      #初始化数量
      initial-size: 1
      #最大连接等待超时时间
      max-wait: 60000
      min-idle: 1
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      web-context-unify: false
    nacos:
      discovery:
      server-addr: 47.100.85.66:8848

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    lazy-loading-enabled: true


