server:
  port: 2001

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  config:
    type: nacos
    nacos:
      server-addr: 47.100.85.66:8848
      group: DEFAULT_GROUP
      data-id: seataServer.properties
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 47.100.85.66:8848
      group: DEFAULT_GROUP
      username: nacos
      password: nacos

spring:
  application:
    name: cloudalibaba-seata-order
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.85.66:8848
        group: DEFAULT_GROUP
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order?characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: wgx
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wgx.springcloud.bean

mybatis-plus:
  configuration:
    lazy-loading-enabled: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
