server:
  port: 9001

spring:
  application:
    name: payment-provider-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.85.66:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
