server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定的规则但是要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后面提供的路由地址
          uri: lb://cloud-payment-service #uri修改为服务名
          predicates:
            - Path=/payment/** #断言，路径相匹配的进行路由
#            - After=2022-05-13T23:28:47.214+08:00[Asia/Shanghai]
#            - Cookie=username, wgx
#            - Header=X-Request-Id, \d+
#            - Method=GET
#            - Query=username, \d+

#        - id: payment_routh2 #路由的ID，没有固定的规则但是要求唯一，建议配合服务名
#            uri: http://localhost:8001 #匹配后面提供的路由地址
#            predicates:
#              - Path=/payment/get/** #断言，路径相匹配的进行路由


eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: gateway9527
    prefer-ip-address: true

