server:
  port: 80


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true

spring:
  application:
    name: cloud-consumer-hystrix-order

feign:
  hystrix:
    enabled: true
#  client:
#    config:
#      default:
#      #\u5EFA\u7ACB\u8FDE\u63A5\u6240\u7528\u7684\u65F6\u95F4\uFF0C\u9002\u7528\u4E8E\u7F51\u7EDC\u72B6\u51B5\u6B63\u5E38\u7684\u60C5\u51B5\u4E0B\uFF0C\u4E24\u7AEF\u8FDE\u63A5\u6240\u9700\u8981\u7684\u65F6\u95F4
#      ConnectTimeOut: 5000
#      #\u6307\u5EFA\u7ACB\u8FDE\u63A5\u540E\u4ECE\u670D\u52A1\u7AEF\u8BFB\u53D6\u5230\u53EF\u7528\u8D44\u6E90\u6240\u7528\u7684\u65F6\u95F4
#      ReadTimeOut: 5000
