server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  rabbitmq:
    host: 47.100.85.66
    port: 5672
    username: admin
    password: wgx
  cloud:
    stream:
      #配置要绑定的rabbitmq的服务信息
      binders:
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
      bindings: #服务整合处理
        output: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的Exchange名称定义
          content-type: application/json #设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit #设置要绑定的消息服务的具体设置

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: stream-provider8801